name: Deploy to mesh-app
on:
  workflow_dispatch:
  push:
    branches: [develop]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mesh-app
    env:
      DEPLOY_ENV: development
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Cache node modules and next folder
      - name: 📬 Caching
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Deploy to Netlify
        id: deploy-netlify
        run: |
          npm i -g netlify-cli
          netlify deploy --prod --build --context develop --debug -m 'GitHub ${{ github.event_name }} CI run ${{ github.run_number }} on behalf of ${{ github.actor }} on ${{ github.ref }} (commit ${{ github.sha }})'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.DEV_NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
